[versions]
#앱의 전반적인 의존성을 가지고 있기 때문에 업데이트 시 유의 해야함
#참고 https://developer.android.com/build/releases/gradle-plugin
#https://mvnrepository.com/artifact/com.android.application/com.android.application.gradle.plugin
androidGradlePlugin = "8.2.1"
kotlin = "1.9.21"
#https://developer.android.com/jetpack/androidx/releases/compose-compiler
androidxComposeCompiler = "1.5.7"

#의존성
#https://developer.android.com/jetpack/androidx/releases/core
coreKtx = "1.12.0"
#androidx.appcompat:appcompat
appcompat = "1.6.1"
#https://mvnrepository.com/artifact/com.google.android.material/material
material = "1.10.0"
#https://developer.android.com/jetpack/androidx/releases/activity
activityCompose = "1.8.1"
#https://developer.android.com/jetpack/compose/bom/bom-mapping
composeBom = "2023.10.01"
#https://developer.android.com/jetpack/androidx/releases/navigation
androidxComposeNavigation = "2.7.5"
#https://developer.android.com/jetpack/androidx/releases/lifecycle
composeLifecycle = "2.7.0"
#https://mvnrepository.com/artifact/com.google.dagger/hilt-android
hilt = "2.48"
#https://developer.android.com/jetpack/androidx/releases/hilt?hl=ko
hiltNavigationCompose = "1.1.0"
#https://central.sonatype.com/artifact/com.squareup.okhttp3/okhttp/4.11.0?smo=true
okhttp = "4.12.0"
#https://github.com/square/retrofit
retrofit = "2.9.0"
#https://plugins.gradle.org/plugin/org.jetbrains.kotlin.plugin.serialization
kotlin-serialization = "1.9.21"
#https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-serialization-json-jvm
kotlin-serialization-json = "1.6.1"
#https://github.com/Kotlin/kotlinx.coroutines
coroutine = "1.7.3"
#https://developer.android.com/jetpack/androidx/releases/datastore?hl=ko
data-store = "1.0.0"
#https://bumptech.github.io/glide/int/compose.html
compose-glide = "1.0.0-beta01"
#https://github.com/ktorio/ktor/releases
ktor = "2.3.7"
#https://developer.android.com/jetpack/androidx/releases/paging
paging = "3.2.1"
#https://mvnrepository.com/artifact/com.google.accompanist/accompanist-permissions
permissions = "0.34.0"
lottieVersion = "6.3.0"
#https://firebase.google.com/docs/analytics/get-started?platform=android&hl=ko#kotlin+ktx
firebase-bom = "32.8.0"
firebase-plugin = "4.3.15"

#test
#https://mvnrepository.com/artifact/junit/junit
junit = "4.13.2"
#https://mvnrepository.com/artifact/androidx.test.ext/junit
androidJunit = "1.1.5"
#https://mvnrepository.com/artifact/androidx.test.espresso/espresso-core
espressoCore = "3.5.1"
#https://developer.android.com/jetpack/androidx/releases/lifecycle?hl=ko
lifecycle = "2.6.2"

#OAuth
#https://developers.kakao.com/sdk/reference/android-rx/release/index.html
kakaoSdk = "2.19.0"

#YutubePlayer
youtube-player = "12.1.0"

#https://github.com/google/accompanist
accompanist = "0.32.0"

[libraries]
#andorid
android-core = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
android-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
android-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

#hilt
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

#compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxComposeNavigation" }
compose-glide = { group = "com.github.bumptech.glide", name = "compose", version.ref = "compose-glide" }
compose-lifeCycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "composeLifecycle" }

#network
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }

#serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization-json" }

#coroutine
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutine" }

androidx-data-store = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "data-store" }

#kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

#test
test-junit = { group = "junit", name = "junit", version.ref = "junit" }
test-android-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidJunit" }
test-android-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

#kakao
kakao-user = { group = "com.kakao.sdk", name = "v2-user", version.ref = "kakaoSdk" }
kakao-share = { group = "com.kakao.sdk", name = "v2-share", version.ref = "kakaoSdk" }

#YoutubePlayer
youtube-player = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "youtube-player" }

#system control
accompanist = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }

#paging
paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }

#permissions
permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "permissions" }

#lottie
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieVersion" }

#firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }

[bundles]
compose = ["compose-ui", "compose-ui-graphics", "compose-ui-graphics", "compose-preview", "compose-ui-tooling", "compose-material3", "compose-navigation", "hilt-navigation-compose", "compose-glide", "compose-ui-util", "compose-lifeCycle"]
ktor-android = ["ktor-core","ktor-client-android", "ktor-client-serialization", "ktor-client-logging", "ktor-negotiation", "ktor-auth"]
ktor = ["ktor-client-serialization", "ktor-client-logging", "ktor-negotiation", "ktor-client-cio", "ktor-auth"]
paging = ["paging", "paging-compose"]
test = ["test-junit", "test-android-junit", "test-android-espresso", "ktor-client-cio"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization" }
firebase-services = { id = "com.google.gms.google-services", version.ref = "firebase-plugin" }